server:
  port: 8080

authKey:
  busArriveInfo: jMHsbEvLniNZoKEEYrOqvg4zpNYXThgIZFRogRrLj%2BfG3utOQPiA9ewldvVXQjv%2FZzagFLE8VWFoBcbz23YYgw%3D%3D
  busStationInfo: jMHsbEvLniNZoKEEYrOqvg4zpNYXThgIZFRogRrLj%2BfG3utOQPiA9ewldvVXQjv%2FZzagFLE8VWFoBcbz23YYgw%3D%3D
  busRouteInfo: jMHsbEvLniNZoKEEYrOqvg4zpNYXThgIZFRogRrLj%2BfG3utOQPiA9ewldvVXQjv%2FZzagFLE8VWFoBcbz23YYgw%3D%3D
  weatherInfo: jMHsbEvLniNZoKEEYrOqvg4zpNYXThgIZFRogRrLj%2BfG3utOQPiA9ewldvVXQjv%2FZzagFLE8VWFoBcbz23YYgw%3D%3D

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/capstone
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    host: 127.0.0.1
    port: 6379
    password: 'chrkb1569'
    channel: foo

jwt:
  secret: VGhpc2lzbXlGaXJzdENhcFN0b25lRGVzaW5nUHJvamVjdCFJV2FudFRvRG9NeUJlc3QhSGF2ZUFOaWNlRGF5IVNQUklOR1NFQ1VSSVRZ
  validationTime : 1800
